### ISSUE TITLE
Consistent Indenting

### ISSUE THREAD

**Issue by cyouh95** [ARB89/prj-rev-bwfs-dasmoto#1]
Try to be a bit more consistent in the indenting of your code. For example, indent only nested elements in your HTML document. This could help improve the readability of your code!

https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L22-L27
https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/recursos/style.css#L30-L38

**Comment by AlejandroRodrigezBravo** [comment]
thanks, I have to train more the white space and nested elements

**Comment by ARB89** [comment]
to clarify the doubt, you mean that I have to do it asin:


<h3 class="Brushes">Brushes</h3>
<img src="./recursos/imagen/hacksaw.jpeg"/>
  <h2>Hacksaw Brushes</h2>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <strong>Starting at $3.00 / brush.</strong></p>

**Comment by AlejandroRodrigezBravo** [comment]
to clarify the doubt, you mean that I have to do it without:
![elementos aninados](https://user-images.githubusercontent.com/36339425/36642312-12942380-1a3e-11e8-950d-9969f3a026ec.JPG)

**Comment by AlejandroRodrigezBravo** [comment]
can you clarify how to do it in css, thanks again.
![css](https://user-images.githubusercontent.com/36339425/36642396-167ee236-1a3f-11e8-9126-bc733a3f66e6.JPG)

**Comment by cyouh95** [comment]
Your HTML in the screenshot looks much better! Just make sure to align the `p` element with the others, as they are all sibling elements:
```html
<h3> ... </h3>
<img ... />
<h2> ... </h2>
<p> ... </p>
```

For your CSS file, each of the properties should be indented (usually 2 spaces):
```css
.texto {
  font-family: Helvetica
  font-size: 100px;
  ...
}
```

**Comment by AlejandroRodrigezBravo** [comment]
ok, thanks
