### ISSUE TITLE
Specification document

### ISSUE THREAD

**Issue by cyouh95** [ARB89/prj-rev-bwfs-dasmoto#2]
In the specifications for this project, the red border around the entire page is there as a guide for you to see the entire layout of the page, but is not actually meant to be part of the design of the page.

https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/recursos/style.css#L4

**Comment by AlejandroRodrigezBravo** [comment]
I had nothing and in the end I decided to put it, and I know for the next projects. Thank you
