### ISSUE TITLE
Good job linking image files

### ISSUE THREAD

**Issue by cyouh95** [ARB89/prj-rev-bwfs-dasmoto#4]
Good job linking all your image files in the HTML document!

https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L15
https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L23
https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L31
https://github.com/ARB89/prj-rev-bwfs-dasmoto/blob/master/Dasmoto%C2%B4s/index.html#L39

**Comment by AlejandroRodrigezBravo** [comment]
thanks
